builders:
  compiler:
    import: "package:jaspr_tailwind/builder.dart"
    builder_factories: [ "buildStylesheet" ]
    build_extensions:
      "web/{{file}}.tw.css":
        - "web/{{file}}.css"
    auto_apply: dependents
    build_to: source
    defaults:
      release_options:
        tailwindcss: --minify
